export const pioneers = [
  {
    name: 'Introduction',
    aka: 'THE ORIGINAL ERA HALL OF FAME',
    desc: 'The Artform of Locking now has several decades of contributors, Each decade has Locking dancers who are now icons in the world of Streetdance, However this room is dedicated to the Many ORIGINAL pioneers,  who deserve recognition for their contribution to the Art and Sub-Culture of Locking.\nMany of these dancers we refer to as Masters or Ogs were around before the Group ‘The Lockers “were presented as a group to the public in 1973. They were there during the sharing and development stages of the dance. These are the dancers who were on Soul Train and in the nightclubs of Los Angeles.\nYES There are many people with different levels of contributions to the history of the art, And lockerlegends looks forward to expanding our Hall to include various phases of contributions, but these are some the ORIGINAL, main & true old school pioneers who contributed steps, style and the attitude which created and contributed to the evolution of the entire sub-culture we know as “Locking”',
    href: '#Introduction',
    url: '',
    img: '/images/mavericksflat.png',
    cName: 'nav-link',
    id: 'Introduction',
  },
  {
    name: 'The term OG',
    aka: 'OG what does it mean?',
    desc: 'The term OG in the street dance of Locking refers to ORIGINAL GENERATION, therefor we acknowledge those who contributed within that era as ORIGINAL OG’s, OG LEGENDS or simply OGs. The  others who did the dance of locking from other eras or decades within locking we refer to as 70s ,80s & 90s 0ldSchool or new school pioneers , or simply BG’s , this terminology is in direct connection with street respect terminology.',
    href: '#The_term_OG',
    url: '',
    img: '/images/watts.jpg',
    cName: 'nav-link',
    id: 'The_term_OG',
  },
  {
    name: 'Don Campbell',
    aka: 'Campbellock',
    desc: 'The creator and Known as the Godfather of Locking & originator of the first Locking moves, combined with gestures That he adapted to his unique rhythm, created the style of dance first known as Campbellocking, and later as it evolved into a dance art form became known as Locking . He was a original member the Soul Train Gang, And established the first improvisational group Called “The Campbellockers”or  Campbellock dancers, Then Later Her was the organizing force behind the group “The Original Lockers” A dynamic soloist, known for his show stoping dives and splits.',
    href: '#Don_Campbell',
    url: '',
    img: '/images/campbell.jpg',
    cName: 'nav-link',
    id: 'Don_Campbell',
  },
  {
    name: 'Damita Jo Freeman',
    aka: 'Damita Jo',
    desc: 'An Original Soul Train Gang member and the first lady of Locking. She was Don Campbells’ first dance partner on the show.  She later won the second Soul Train Dance contest, displaying her unique Locking style with then partner Jimmy “Scooby doo” Foster. Known for her high leg kicks, she went on to become one of the industries most noted choreographers',
    href: '#Damita_Jo_Freeman',
    url: '',
    img: '/images/damita.jpg',
    cName: 'nav-link',
    id: 'Damita_Jo_Freeman',
  },
  {
    name: 'Greg Pope',
    aka: 'Campbellock Jr',
    desc: 'Greg was not related to Don Campbell but given the name because of his creativity with locking movements. A member of the Soul Train Gang and Locking Dance group from  The watts writers workshop “Creative Generation” before joining the Original Lockers in 1973. Greg helped to create several steps, moves, handshakes and routines associated with Locking.',
    href: '#Greg_Pope',
    url: '',
    img: '/images/greg.png',
    cName: 'nav-link',
    id: 'Greg_Pope',
  },
  {
    name: 'Fred Berry',
    aka: 'Rerun / Penguin',
    desc: 'He is also known as Rerun on the 1970’s TV sitcom “Whats Happening”. A Soul Train Dancer and member of the first improvistional group “The Cambellockers”and a member of the Original Lockers.  His wide body and smile was associated with his introduction of the slow motion and his signature move the master butt drop.',
    href: '#Fred_Berry',
    url: '',
    img: '/images/Fredberry.png',
    cName: 'nav-link',
    id: 'Fred_Berry',
  },
  {
    name: 'Leo Williams',
    aka: 'Fluky Luke',
    desc: 'A soul train dancer and original member of the Lockers  was known for his double jointed locks known as “Leo locks”.  He also contributed various sychronized steps such as the which-a-way to the locking sub-culture.',
    href: '#Leo_Williams',
    url: '',
    img: '/images/flukyluke.png',
    cName: 'nav-link',
    id: 'Leo_Williams',
  },
  {
    name: 'Jimmy Foster',
    aka: 'Scoo B Doo',
    desc: 'A member of the Original Soul Train Gang, along with then Partner Damito Jo Freeman used their Locking styles to win the second Soul Train Dance contest. He Later bacame a member of the Watts Writers “Creative Generation”1972-1973 and went on to dance with “Something Special” and become one of the first Chip”n”dale dancers. Scooby was a long tall animated dancer, who was often seen developing locking handshakes and steps along with Greg Campbellock Jr. but probaly the most noted for the step he created known as the Scoobydoo.',
    href: '#Jimmy_Foster',
    url: '',
    img: '/images/scoobdoo.png',
    cName: 'nav-link',
    id: 'Jimmy_Foster',
  },
  {
    name: 'James Higgins',
    aka: 'O.G Skeeter Rabbit',
    desc: 'Is an early Soul Train Dancer and member of several early locking groups. The Original Go-Go Brothers 1971 to 1973, Watts Writers  “Creative Generation” 1972 to 1973 and the Original Lockers 1973 to 1974. He also danced with the Ghetto Dancers in 1975 and was also known as an outstanding master robot. He later organized and toured with the Locking group 33rpm in late 1975.  He was most known for his creation of the dance step done in most syncronized locking routines called “The skeeterrabbit”.',
    href: '#James_Higgins',
    url: '',
    img: '/images/Skeet.png',
    cName: 'nav-link',
    id: 'James_Higgins',
  },
  {
    name: 'Arnetta Johnson',
    aka: 'Netta Bug',
    desc: 'An Original Locking Streetdancer, and the very First female dancer to dance in a Locking group, NettaBug was very instramental with her strong fundamental Locking, She was a high school chearleader and was often sceen at the clubs as well as the streetparties and high school dances along with the GoGo brothers , here connection with the watts writers workshop prompted the Organization of the First unisex Locking Group “Creative Generation” She was also a member of the First all Female Locking group “The Toota Woota Sisters” Many who saw the Lockers believe Tony Basil to have been a first. but these females came years before.',
    href: '#Arnetta_Johnson',
    url: '',
    img: '/images/ArnettaJohnsson.png',
    cName: 'nav-link',
    id: 'Arnetta_Johnson',
  },
  {
    name: 'Anthony Lewis',
    aka: 'Tony Gogo',
    desc: ' An early Soul Train Dancer and a founding member of the Go Go Brothers dance group in the early 1970s’.  He also danced with groups like 33rpm and was a member of the “Original Lockers”.  Tony had a quick acrobatic style. He and other Go Go Brother members are credited with the first sycronized locking group 1971. Tony went on to introduce and establish locking styles and instruction in Japan',
    href: ' #Anthony_Lewis',
    url: '',
    img: '/images/tonygogo.png',
    cName: 'nav-link',
    id: 'Anthony_Lewis',
  },
  {
    name: 'Adolfo Quinones',
    aka: 'Shabba-Doo',
    desc: 'Originally from Chicago, one of the Original members of The Lockers Group. He was also known for his charactor “O Zone” in the “Breaking movies. Shab was one of the last to be introduced into the original locking circuit in 1973.Two years after the evolutionary stage had began. but He quicky became one of the quickest and smoothest dancers around. His first nickname was “King Rookie” because of his ability to absorb routeins at a quick pace.',
    href: '#Adolfo_Quinones',
    url: '',
    img: '/images/Shabbadoo.png',
    cName: 'nav-link',
    id: 'Adolfo_Quinones',
  },
  {
    name: 'Bill Williams',
    aka: 'Slim the Robot',
    desc: 'Early Soul Train Dancer who was known for doing the Robot. Slim went on to tour with the improvistional dancers known as the “Campbellock dancers” and was an Original Member of the “Original Lockers”. He reinovated the basic robot style into a quick karate style robot movement and was also known for introducing a colored light suit and flame throwing capabilities into his act.',
    href: '#Bill_Williams',
    url: '',
    img: '/images/billwilliams.png',
    cName: 'nav-link',
    id: 'Bill_Williams',
  },
  {
    name: 'Edwin Lombard',
    aka: 'Buddy Go-Go',
    desc: 'Edwin was another member of the Go-Go brothers dance group also a member of the first unisex Locking group Watts Writers’ Creative Generation, Buddy with other Tony Go-Go and Skeeter Rabbit implimented many early sychronized steps and skits',
    href: '#Edwin_Lombard',
    url: '',
    img: '/images/edwinlombard.png',
    cName: 'nav-link',
    id: 'Edwin_Lombard',
  },
  {
    name: 'Freddie Maxie',
    aka: 'Freddie Maxie',
    desc: 'She was an early street dancer from the Compton street dance era,who became a soul train dancer , and has been the dance partner to many legendary Lockers, she was one of the earliest Female Lockers , who spent time both in the clubs, street parties and in various performance groups like “something special” & “The soul Train Gang”',
    href: '#Freddie_Maxie',
    url: '',
    img: '/images/freddiemaxie.png',
    cName: 'nav-link',
    id: 'Freddie_Maxie',
  },
  {
    name: 'Alpha Andersson',
    aka: 'Alpha Omega',
    desc: 'Is a unique style Locking dancer, Alpha was an early 1970s’ soul train dancer,who created a unique style of Russian kicks by bouncing back on  hands between kicks, This step known as    “Alphas” are still done by many lockers  Alpha was a member of the second generation of the Group “The Lockers',
    href: '#Alpha_Andersson',
    url: '',
    img: '/images/alpha.png',
    cName: 'nav-link',
    id: 'Alpha_Andersson',
  },
  {
    name: 'Johnnie McCloud',
    aka: 'Sambo Lock',
    desc: 'Although “Sambo” danced for only a short time (early 1970s’) he was very influential in locking development. He was on tour with the improvasation dancers known as the “Campbellock dancers”. Known for his continous kick splits and is credited with the first known buttdrop which he titled “The Pancake".',
    href: '#Johnnie_McCloud',
    url: '',
    img: '',
    cName: 'nav-link',
    id: 'Johnnie_McCloud',
  },
  {
    name: 'Toni Basil',
    aka: 'Toni',
    desc: 'She was an already accomplished choreograher when she learned to lock from Don Campbell and was an organizing force in development of the Group the “Original Lockers”.  Toni had an extensive ballet background and eventually became the only female in the original Lockers Group, although Basil is not from the Original Movement of Locking her contribution as a manager should be acknowledged, without her connections and showbussiness expierience the Lockers would not have been able to obtain the professional , or reach the commercial Level of acceptance as they did, she is most noted for incorperating her ballet into locking and her continuous spins.',
    href: '#Toni_Basil',
    url: '',
    img: '/images/tonibasil.png',
    cName: 'nav-link',
    id: 'Toni_Basil',
  },
  {
    name: 'Charles Washington',
    aka: 'Charles the Robot',
    desc: 'He was around from the very beginning. when Robots & Locking was both classified as Lockers, Charles is considered the Godfather of the Party dance of the  Robot style within Locking. Prior to its evolution into the Popping scene. He was  a member of the first Soul Train Gang, and toured with the improvisation dancers known as The “Campbellock Dancers” in 1972. He was the originator of the Robot style of rythimic dancing and organized the group, “The Robot Brothers” in the late 1960s’.',
    href: '#Charles_Washington',
    url: '',
    img: '',
    cName: 'nav-link',
    id: 'Charles_Washington',
  },
  {
    name: 'Others',
    aka: '(Image is not connected to the names',
    desc: 'Kevin “YoYo” Lombard :see the GoGo Brothers page, \n Eugine Henderson “F&M”,\n Steve Crane ” Sinbad” see:The Ghetto dancers,\n Greg Dandridge “Captain,\n Crunch”see The Ghetto Dancers,\n Mike Frenke “Peekaboo” see: 33rpm & YoYo brothers,\n Guy Evan “Shocklock”,\n John “OkieDoke” Wilson see 33rpm,\n Jeffrey Daniel,\n Tito Collins see: The Alphebet kids & 33rom,\n Jeffery McKintire “Cat Man”,\n Bishop “CoCo” Hall,\n Tick, Sneaky T,\n Enock “Elmer Fud” Smith (RIP),\n',
    href: '#Others',
    url: '',
    img: '/images/others.png',
    cName: 'nav-link',
    id: 'Others',
  },
];

/* 
{
    name: ' ',
    aka: ' ',
    desc: '',
    url: '',
    img: '',
    cName: 'nav-link',
    id: '',
  },

*/
