export const steps = [
  {
    name: 'BASIC LOCK',
    desc: "The hesitating or Freezing of the Arms to the beats of the music, where created By Don Campbell the Late 1960s, early 1970s as he paused or froze while trying to do a popular social dance called the 'funky chicken' between doing this and various other social dances and stunts.The pauses became known as locks or locking up.Later in the development Leo” Flukey Luke Williamson”introduced a unique Lock by placing the outer ridge of both of his hands on his waist and locking his elbows forward this became known as the 'Leo Lock'",
    creator: 'Don Campbellock Campbell',
    id: '1',
  },
  {
    name: 'GIVING OR ASKING FOR FIVE',
    desc: 'This is a hand slap that acknowledges an agreement either between Two people or oneself while dancing , Don Campbell incorporated this in between his Locks and social dances, The origin of Giving Five or Receiving Five had long been a tradition of acknowledgement in the Afro American community. This was an established ritual prior to Don incorporating it into his dancing. As people would smile and acknowledge there approval of a move, Don and other pioneers would often offer there hand (to recieve five),accepting a hand slap back was accepting approval. For a move or step. Giving Five is acknowledging something good taking place. Points.',
    by: '',
    id: '2',
  },
  {
    name: 'LOCKING POINTS',
    desc: 'Later refered to as Uncle Sam points, for the U.S. armed forces recruiting poster, which featured the Uncle Sam caricature recruiting by pointing out a message .. Also pointing at a friend or partner was also a message or an acknowledgement in the African American Community, This was also a ritual of communication and was often done when two people had to greet across a distance even prior to it being incorperated, by Don Campbell into his dance style. The story goes , that while Don was dancing, a lady at a table was laughing at his unique style, So Don did what everyone was doing, he pointed at her to let her know that he saw her. and this was the very first and basic Locking point.Later as the dance developed double and triple points were introduced by other pioneers causing a more free flowing rythem to Locking.',
    by: '',
    id: '3',
  },
  {
    name: 'HAND CLAPS',
    desc: 'Back hand claps and Backfront hand claps were also very basic in the beginning , stopping and starting abruptly, they were often done alone while pacing or in-between other moves, Don also incoorperated the very first wristrolls into his style. later various combinations of wrist rolls and other moves were incorporated and done before backfront hand claps, Again this contributed to the continuity and evolution of the dance.',
    by: '',
    id: '4',
  },
  {
    name: 'UPLOCK',
    desc: 'The UPLOCK or what is today refered to as the Muscle man, is the throwing up of both arms usually the start of a locking move, This move was an announcement ,Much like gesture used on the streets as a greeting, saying “Hey” or “whats up on the street”',
    by: '',
    id: '5,',
  },
  {
    name: 'THE DON CAMPBELL WALK',
    desc: 'This was created by Don Campbell, himself it was  sliding stepping movement used by Don to move forward in between Locks and stunts',
    by: '',
    id: '6',
  },
  {
    name: 'THE SCOOBY DOO',
    desc: 'created by Jimmy “Scooby doo “Foster, the basic scooby doo,is two handed up lock anouncement followed by a kick, step',
    by: '',
    id: '7',
  },
  {
    name: 'THE SCOOBOT',
    desc: 'Also by Jimmy “Scooby doo “Foster, the basic scoobot, is a unique step that ',
    by: '',
    id: '8',
  },
  {
    name: 'THE HITCHHIKE',
    desc: 'Imitating hitchhike:in, sideways with a thumbs up and mixing with rocksteady:s funky hip groove',
    by: '',
    id: '9',
  },
  {
    name: 'THE SCOOBY WALK',
    desc: 'Jimmy Fosters way of walking, similar to what Greg called the pimpwalk',
    by: '',
    id: '10',
  },
  {
    name: 'THE PIMP WALK',
    desc: 'Created by Greg “Campbellock Jr. “ Pope , many of the move Greg instituted into locking helped promote the free flow and continunity into the style, Greg also modified the scoobot into a hop move, some of the above mentioned moves such as the Sneek & The stop n go (Quickies) where created by Jimmie “Scoobydo” Foster , with impute from Greg Campbellock Jr. and many of these moves were named by Damita Jo Freeman',
    by: '',
    id: '11',
  },
  {
    name: 'SNEEK',
    desc: 'The sneek was a variation of the soul dance the breakdown ,but the upper body twisted from side to side swinging the outside arms up in a searching motion, later the inside arm was used by the lockers  to allow camera angles during commercial performances.',
    by: '',
    id: '12',
  },
  {
    name: 'QUICKIES /STOP N GO',
    desc: "Qickies, (sometimes called stop n go's) became a variation of the old sara walk dance move, but the quick movement imitaded the rubberband up move of a cartoon character.",
    by: '',
    id: '13',
  },
  {
    name: 'THE SKEETERRABBIT',
    desc: 'created by James “Skeeter Rabbit “Higgins, This step was inspired by the shuffle moves of the nicholas brothers , and the street game of hop scottch, as skeeter added this ending onto the scoobydoo ,it became a continuous movement,that he did various ways. Also variations of skeeterrabbit shuffles added by several other pioneers. The most notable was in the mid 1970s with the blending and acceptance of the street gang culture dance movement with Locking when the streetdance known as the CRIP WALK was first introduced as a finishing move added on to the Skeeterrabbit by Micheal “Peekaboo” Frenke and Leo “Shaboo” Walker ',
    by: '',
    id: '14',
  },
  {
    name: 'HAT TWIRLES',
    desc: 'introduced into Locking, Had been done by various entertainers in history. ,The move was adapted by several locking dancers ,the most notables were “Sneeky T” and John “Okey Doke” Wilson” It Later became known as one of Don Campbells signiture moves , but the basic hat spin was first taught to Don in 1974 by SKEETER RABBIT, while on the Lockers first major tour.',
    by: '',
    id: '15',
  },
  {
    name: 'THE WHICH A WAY',
    desc: 'The WhichaWay introduced by Leo “ Flukey Luke “ Williamson into a signature , locking move, However it was originally created as a social party dance step By Damita Jo Freeman who did a modified style of the step by turning her hips in a slower motion than done by Flukey . she originally called this version the “DJ which a way,”she can be seen doing this version on various soul train clips',
    by: '',
    id: '16',
  },
  {
    name: 'THE LEO LOCK',
    desc: 'The Leo Lock was done by Leo and other double jointed Lockers who were able to lock their arms with their hands on their hips and their elbows in front of them. ',
    by: '',
    id: '17',
  },
  {
    name: 'LEO WALK',
    desc: 'Leo walk is a side to side stepping and rocking motion',
    by: '',
    id: '18',
  },
  {
    name: 'KILLING ROACHES',
    desc: 'Killing roaches ws inspired from ghetto living, as one would slap the floor as if trying to kill bugs to the rythem of the music',
    by: '',
    id: '19',
  },
  {
    name: 'THE SLOW MOTION',
    desc: 'introduced in Locking by Fred “ Mr. Penguin “ Berry, the slowmotion was a mime style imitation of locking, where everthing was slowed down and facial expressions was emphisized,',
    by: '',
    id: '20',
  },
  {
    name: 'THE VOLKSWAGON',
    desc: 'the volkswagon was inspired by the driving of an mannual shift car, it imitated shifting and the lunging of a car to the rythem of the music, ',
    by: '',
    id: '21',
  },
  {
    name: 'THE HELICOPTOR',
    desc: 'The helecopter was Pinguins way of pointing and acknowledging everyone around him in one continuous move',
    by: '',
    id: '22',
  },
  {
    name: 'THE KEEPA RUNNIN',
    desc: 'created by Tony Lewis and Buddy Lombard ( GoGo Bros) the keepa runnin was a footwork, kick step slide move',
    by: '',
    id: '23',
  },
  {
    name: 'The Sara Walk',
    desc: 'the sara walk was a front back pace move,',
    by: '',
    id: '24',
  },
  {
    name: 'THE SUPER FLY',
    desc: '',
    by: '',
    id: '25',
  },
  {
    name: 'THE “ALPHA”',
    desc: 'A Fall back handspring type Floormove  created and introduced into a unique style of of Locking by Alpha Omega Anderson, This included a spinning fast corkscrew style of Locking',
    by: '',
    id: '26',
  },
  {
    name: 'STUNTS & SPLITS',
    desc: 'Half Splits had often been done while dancing by previous entertainers, both singers and dancers , Dance groups like the Nicholas Brothers and The Sammy Davis Jr. Trio. In the 1960s/ 70s James Brown made the half split popular. Imitating The James Brown Dance and Steps that he did on stage was widely done in African American Social Parties this included half splits and floor moves called “The Alligator” Many moves and styles, such as the “camel walk“, the “mash potatoes” were incorporated from James Browns act.He was a tremendous influence Don Campbell also following the party influence, continued to do Half Splits and floor moves like Knee dropsin between his social Dancing and Locks, KICK SPLITS introduced into Locking by Don Campbell but done by James Brown , many tap dancers and party dancers prior. HIGH FLYING KNEE DROPS RUNNING KNEE DROPS as well as The SWAN Dive became part of Don Campbell instituted this into his style.',
    by: '',
    id: '27',
  },
  {
    name: 'BUTT DROPS',
    desc: 'created by John “ Sambo Lock “ McCloud, a dynamic and daring stunt, where the dancer would jump and leve both feet out in front of him , landing on his but in time with a beat in the music',
    by: '',
    id: '28',
  },
  {
    name: 'LOCKING HAND SHAKES',
    desc: 'First seen done by Damita Jo Freeman and Jimmy “Scooby Doo Foster during The soul train Dance contest, Some Locking Handshakes were created by Greg “Campbellock “ Pope , First done by Greg Cambellock Jr and Flukey Luke (see the video Watts Stax.) Several other handshakes were introduced by the ( GoGo Brothers)These hand shakes were representing the unity handshakes done on the streets of the inner city.',
    by: '',
    id: '29',
  },
  {
    name: 'THE ROBOT',
    desc: 'Although technically The Robot is not a Lock, Roboting has always been a part of Locking from the friendship of Don Campbell and Charles “ROBOT” Washington, It was incorporated into both the evolutionary Locking movement and in the commercial Locking Performances.. so it will be forever linked Roboting was introduces as a dance and into the Locking Subculture by Charles “Robot “Washington',
    by: '',
    id: '30',
  },
  {
    name: '',
    desc: '',
    by: '',
    id: '31',
  },
  {
    name: '',
    desc: '',
    by: '',
    id: '32',
  },
];
